[package]
name = "hello-rs"
version = "0.0.1"
authors = ["Krenodeno"]
edition = "2018"

[lib]
name = "hellors"
crate-type = ["dylib"]

[dependencies]
cpython = "0.7"

[features]
default = ["python3"]
python3 = ["cpython/python3-sys", "cpython/extension-module"]